name: Dependabot auto-merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      # 检查当前 PR 是否所有状态检查都通过
      - name: Wait for status checks
        uses: actions/github-script@v7
        id: checks
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const { data: combined } = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            if (combined.state !== 'success') {
              core.setFailed(`Not all required checks have passed. Current state: ${combined.state}`);
            }

      # 所有检查通过后启用自动合并
      - name: Enable auto-merge for Dependabot PRs
        if: success()
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.html_url }}
          merge-method: squash
