name: 单元测试

on: [push, pull_request, workflow_dispatch]

# 添加权限配置
permissions:
  contents: read
  checks: write  # 授予创建检查运行的权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0  # 获取完整的git历史用于版本信息
    - name: 设置JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: 设置 Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: 设置 Gradle 可执行权限
      run: chmod +x ./gradlew
    - name: 使用Gradle构建
      run: ./gradlew build -x test
    - name: 运行单元测试
      run: ./gradlew test
    - name: 测试报告
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: 测试结果
        path: build/test-results/test/*.xml
        reporter: java-junit